controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\application\entities\Dish;
use app\application\entities\Ingredient;

class AdminController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['@'],
                    ]
                ]
            ]
        ];
    }

    public function actionIndex()
    {
        $message = Yii::$app->request->get()['message'] ?? null;

        return $this->render('index', [
            'dish_index_data_provider' => Dish::getDishProvider(),
            'ingredient_index_data_provider' => Ingredient::getIngredientProvider(),
            'message' => $message
        ]);
    }
}

controllers/BookController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\application\entities\Book;
use app\application\entities\Dish;

class BookController extends Controller
{
    private const LANGUAGE_ALIAS_LIST = [
        'ru'=>'Russian',
        'en'=>'English'
    ];

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionList()
    {
        return $this->render('list', [
            'books'=>Book::getFullBooksList(),
            'languages'=>static::LANGUAGE_ALIAS_LIST
        ]);
    }


    public function actionSingle($id)
    {
        return $this->render('single', [
            'dishes'=>Book::getBookDishes($id),
            'book_name'=>Book::getBookName($id)
        ]);
    }
}

controllers/DishController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\behaviors\FindModelBehavior;
use app\behaviors\ResponseActionBehavior;
use app\application\services\dish\DishAddService;
use app\application\services\dish\DishUpdateService;
use app\application\entities\Dish;

class DishController extends Controller
{
    private const NEW_DISH_SUCCESS_ADD = 'Новое блюдо успешно добавлено';

    private const NEW_DISH_ERROR_ADD = 'Произошла ошибка при добавлении нового блюда';

    private const DISH_SUCCESS_DELETE = 'Блюдо успешно удалено';

    private const UPDATE_DISH_WITHOUT_NAME = 'Ошибка при обновлении. У блюда должно быть название';

    private const TOO_FEW_INGREDIENTS_FOR_UPDATE_DISH = 'Ошибка при обновлении. У блюда остается слишком мало ингредиентов';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@'],
                    ]
                ]
            ],
            'FindModelBehavior'=>FindModelBehavior::className(),
            'ResponseActionBehavior'=>ResponseActionBehavior::className(),
        ];
    }

    public function actionCreate()
    {
        $add_data_service = new DishAddService();
        return $this->render('create', $add_data_service->getCreateWindowData());
    }

    public function actionUpdate($id)
    {
        $update_data_service = new DishUpdateService();
        return $this->responseAction($update_data_service->getUpdateWindowData($id));
    }

    public function actionDelete($id)
    {
        $this->findModel($id, new Dish())->delete();
        return $this->redirect(['/admin?message='.static::DISH_SUCCESS_DELETE]);
    }

    public function actionView($id)
    {
        return $this->render('single', [
            'dish'=>Dish::getDishData($id)
        ]);
    }

    public function actionSave()
    {
        return $this->redirect(Dish::saveNewDish());
    }
}

controllers/IngredientController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\behaviors\ResponseActionBehavior;
use app\application\services\ingredient\IngredientManageService;

class IngredientController extends Controller
{
    private $ingredient_manage_service;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@'],
                    ]
                ]
            ],
            'ResponseActionBehavior'=>ResponseActionBehavior::className(),
        ];
    }

    public function beforeAction($action)
    {
        $this->ingredient_manage_service = new IngredientManageService();
        return parent::beforeAction($action);
    }

    public function actionCreate()
    {
        return $this->responseAction($this->ingredient_manage_service->createNewIngredient());
    }

    public function actionUpdate($id)
    {
        return $this->responseAction($this->ingredient_manage_service->updateDataForIngredient($id));
    }

    public function actionDelete($id)
    {
        return $this->redirect($this->ingredient_manage_service->deleteIngredient($id));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\application\forms\LoginForm;
use app\application\services\dish\DishSearchService;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionSearch()
    {
        $search_service = new DishSearchService();
        return $this->render('search', $search_service->getSearchWindowDataContent());
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            $this->redirect(Yii::$app->homeUrl);
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/admin']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

views/admin/_dish_list.php
<?php
use app\helpers\UrlTransform;
use yii\helpers\Html;
use yii\grid\GridView;
?>

<?php
    echo GridView::widget([
        'dataProvider'=>$dish_index_data_provider,
        'columns'=>[
            [
                'attribute'=>'id',
                'headerOptions'=>['width'=>40],
                'contentOptions'=>[
                    'class'=>'admin-grid-id-param'
                ]
            ],
            [
                'attribute'=>'name',
                'label'=>'Название',
                'contentOptions'=>[
                    'class'=>'admin-grid-name-param'
                ]
            ],
            [
                'class'=>'yii\grid\ActionColumn',
                'headerOptions'=>['width'=>50],
                'template'=>'{update}{delete}',
                'buttons'=>[
                    'update'=>function ($url, $model) {
                        return Html::a('&#9998;', 'dish/update/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    },
                    'delete'=>function ($url, $model) {
                        return Html::a('&#10006;', 'dish/delete/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    }
                ]
            ]
        ],
        'summaryOptions'=>[
            'class'=>'admin-grid-summary'
        ],
        'layout'=>'{summary}{items}<div class="catalog-tile-pager">{pager}</div>',
        'rowOptions'=>[
            'class'=>'admin-grid-row'
        ],
        'tableOptions'=>[
            'class'=>'admin-grid-table'
        ],
        'options'=>[
            'class'=>'admin-grid-container'
        ]
    ]);
?>

views/admin/_ingredient_list.php
<?php
use app\helpers\UrlTransform;
use yii\helpers\Html;
use yii\grid\GridView;
?>

<?php
    echo GridView::widget([
        'dataProvider'=>$ingredient_index_data_provider,
        'columns'=>[
            [
                'attribute'=>'id',
                'headerOptions'=>['width'=>40],
                'contentOptions'=>[
                    'class'=>'admin-grid-id-param'
                ]
            ],
            [
                'attribute'=>'name',
                'label'=>'Название',
                'contentOptions'=>[
                    'class'=>'admin-grid-name-param'
                ]
            ],
            [
                'attribute'=>'hidden',
                'label'=>'Скрытый',
                'headerOptions'=>['width'=>90],
                'contentOptions'=>[
                    'class'=>'admin-grid-hidden-param'
                ],
                'content'=>function ($data) {
                    return ($data->hidden)?'Да':'Нет';
                }
            ],
            [
                'class'=>'yii\grid\ActionColumn',
                'headerOptions'=>['width'=>50],
                'template'=>'{update}{delete}',
                'buttons'=>[
                    'update'=>function ($url, $model) {
                        return Html::a('&#9998;', 'ingredient/update/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    },
                    'delete'=>function ($url, $model) {
                        return Html::a('&#10006;', 'ingredient/delete/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    }
                ]
            ]
        ],
        'summaryOptions'=>[
            'class'=>'admin-grid-summary'
        ],
        'layout'=>'{summary}{items}<div class="catalog-tile-pager">{pager}</div>',
        'rowOptions'=>[
            'class'=>'admin-grid-row'
        ],
        'tableOptions'=>[
            'class'=>'admin-grid-table'
        ],
        'options'=>[
            'class'=>'admin-grid-container'
        ]
    ]);
?>

views/admin/index.php
<?php
use yii\helpers\Html;
$this->title = 'Административный раздел';
?>

<?php if (!empty($message)): ?>
    <div class="admin-message">
        <?= $message ?>
    </div>
<?php endif; ?>

<div class="admin-main-container">
    <div class="admin-dish-list">
        <h3>Блюда</h3>

        <?= $this->render('_dish_list', [
            'dish_index_data_provider'=>$dish_index_data_provider
        ]); ?>

        <?= Html::a('Добавить блюдо', '/dish/create', ['class'=>'standart-button admin-dish-add-button']) ?>
    </div>
    <div class="admin-ingredient-list">
        <h3>Ингредиенты</h3>
        <?= $this->render('_ingredient_list', [
            'ingredient_index_data_provider'=>$ingredient_index_data_provider
        ]); ?>

        <?= Html::a('Добавить ингредиент', '/ingredient/create', ['class'=>'standart-button admin-ingredient-add-button']) ?>
    </div>
</div>

views/book/_book_dishes_list.php
<?php
use app\helpers\HtmlClassTransform;
?>

<div class="single-book-dishes-list">
    <?php foreach ($dishes as $dish): ?>
        <a class="books-item-common-style single-book-dishes-list-item clearfix" href="/dish/<?= $dish->id ?>">
            <div class="book-dishes-list-item-name">
                <?= $dish->name ?>
            </div>
            <div class="book-dishes-list-item-complexity <?= HtmlClassTransform::getComplexityBackgroundClassName($dish->complexity) ?>">

            </div>
            <div class="book-dishes-list-item-description">
                <?= $dish->description ?>
            </div>
        </a>
    <?php endforeach; ?>
</div>

views/book/_books_list.php
<div class="books-list">
    <?php foreach($books as $book): ?>
        <a class="books-list-item books-item-common-style" href="/book/<?= $book->id ?>">
            <div class="book-list-item-name">
                <?= $book->name ?>
            </div>
            <div>
                Language: <?= $languages[$book->language] ?>
            </div>
            <div>
                Year: <?= date_parse($book->year)['year'] ?>
            </div>
            <div>
                Description: <?= $book->description ?>
            </div>
        </a>
    <?php endforeach; ?>
</div>

views/book/list.php
<?php
$this->title = 'Книги рецептов';
?>

<?= $this->render('_books_list', [
        'books'=>$books,
        'languages'=>$languages
]); ?>

views/book/single.php
<?php
$this->title = 'Книга "'.$book_name.'"';
?>

<?= $this->render('_book_dishes_list', [
        'dishes'=>$dishes
]); ?>

views/dish/_form.php
<?php
//use Yii;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<?php $form = ActiveForm::begin([
        'id' => 'dish-manage-model',
        'options'=>[
        ]
    ]); ?>

    <?= $form->field($dish_model, 'name', ['options'=>['label'=>'Название', 'class'=>'dish-manage-form-field']])
            ->textInput(['class'=>'dish-manage-field-input', 'placeholder'=>'Введите название', 'value'=> $dish_model->name ?? Yii::$app->session->get('new_dish_name')])
            ->label('Название') ?>

    <?= $form->field($dish_model, 'choice_ingredient', ['options'=>['label'=>'Выберите ингредиент','class'=>'dish-manage-form-field']])
            ->listBox($available_ingredient_list, ['class'=>'dish-manage-field-list'])
            ->label('Выберите ингредиент') ?>

    <?= Html::submitButton($name_button_action, ['class' => 'standart-button dish-manage-button', 'name' => 'dish-manage-button']) ?>
<?php ActiveForm::end(); ?>

views/dish/_ingredients_list.php
<?php
use yii\helpers\Html;
?>

<?php foreach ($manage_dish_ingredients_list as $manage_ingredient): ?>
    <div>
        <span><?= $manage_ingredient['name'] ?></span>
        <?= Html::a('&#10006;', $url_action_link.$manage_ingredient['index'], ['class' => 'dish-manage-delete-button']) ?>
    </div>
<?php endforeach; ?>

views/dish/book.php
<?php
$this->title = 'Книга';
?>

views/dish/create.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Добавление блюда';
?>

<?php if (!empty($message)): ?>
    <div class="admin-message">
        <?= $message ?>
    </div>
<?php endif; ?>

<div class="dish-manage-container">

    <div clas="dish-manage-form">
        <?= $this->render('_form', [
            'dish_model'=>$dish_model,
            'name_button_action'=>'Добавить',
            'available_ingredient_list'=>$available_ingredient_list
        ]); ?>
        <?= Html::a('Сохранить', '/dish/save', ['class' => 'standart-button dish-manage-button']) ?>
    </div>

    <div class="dish-manage-ingredient-list">
        <?= $this->render('_ingredients_list', [
            'dish_model'=>$dish_model,
            'url_action_link'=>'/dish/create?discard=',
            'manage_dish_ingredients_list'=>$manage_dish_ingredients_list
        ]); ?>
    </div>

</div>

views/dish/single.php
<?php
use app\helpers\HtmlClassTransform;
$this->title = '"'.$dish['info']->name.'"';
?>

<div class="single-dish-content-container">
    <div class="single-dish-content-name">
        <h3><?= $dish['info']->name ?></h3>
    </div>
    <div class="single-dish-content-description">
        <?= $dish['info']->description ?>
    </div>
    <div class="single-dish-content-info-label">
        Книга рецептов: <?= $dish['book']->name ?>
    </div>
    <div class="single-dish-content-info-label">
        Сложность: <span class="<?= HtmlClassTransform::getComplexityColorClassName($dish['info']->complexity) ?>">
            <?= HtmlClassTransform::getComplexityReadableName($dish['info']->complexity) ?>
        </span>
    </div>
    <div class="single-dish-content-ingredients-label">
        Ингредиенты:
    </div>
    <div>
        <?php foreach($dish['ingredients'] as $ingredient): ?>
            <div class="single-dish-ingredient-item">
                &#9658; <span class="single-dish-ingredient-name"><?= $ingredient->name ?></span>
            </div>
        <?php endforeach; ?>
    </div>
</div>

views/dish/update.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Редактирование блюда '.$dish_model->name;
?>

<?php if (!empty($message)): ?>
    <div class="admin-message">
        <?= $message ?>
    </div>
<?php endif; ?>

<div class="dish-manage-container">

    <div clas="dish-manage-form">
        <?= $this->render('_form', [
            'dish_model'=>$dish_model,
            'name_button_action'=>'Добавить',
            'available_ingredient_list'=>$available_ingredient_list
        ]); ?>
    </div>

    <div class="dish-manage-ingredient-list">
        <h3>Текущие ингредиенты</h3>
        <?= $this->render('_ingredients_list', [
            'dish_model'=>$dish_model,
            'url_action_link'=>'/dish/update/'.$dish_model->id.'?discard=',
            'manage_dish_ingredients_list'=>$manage_dish_ingredients_list
        ]); ?>
    </div>

    <div class="dish-manage-info-list">
        <div class="dish-manage-description-container">
            
        </div>
        <div class="dish-manage-complexity-field">

        </div>
        <div class="dish-manage-book-field">

        </div>
    </div>
</div>

views/ingredient/_form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<?php $form = ActiveForm::begin([
        'id' => 'ingredient-manage-model',
        'options'=>[
            'class'=>'ingredient-manage-form'
        ]
    ]); ?>

    <?= $form->field($ingredient_model, 'name', ['options'=>['class'=>'ingredient-manage-form-field']])->textInput(['class'=>'ingredient-manage-field-input', 'placeholder'=>'Введите название']) ?>
    <?= $form->field($ingredient_model, 'hidden', ['options'=>['class'=>'ingredient-manage-form-field']])->checkbox(['class'=>'ingredient-manage-field-checkbox']) ?>

    <?= Html::submitButton($button_label, ['class' => 'standart-button ingredient-manage-button', 'name' => 'ingredient-manage-button']) ?>
<?php ActiveForm::end(); ?>

views/ingredient/create.php
<?php
$this->title = 'Добавление ингредиента';
?>

<?= $this->render('_form', [
        'ingredient_model'=>$ingredient_model,
        'button_label'=>'Добавить'
    ]); ?>

views/ingredient/update.php
<?php
$this->title = 'Редактирование ингредиента';
?>

<?= $this->render('_form', [
        'ingredient_model'=>$ingredient_model,
        'button_label'=>'Редактировать'
    ]); ?>

views/layouts/_high_menu.php
<?php
use yii\helpers\Html;
?>

<?php if (Yii::$app->request->url !== '/' && Yii::$app->request->url !== '/index'): ?>
    <?= Html::a('Главная', '/', ['class'=>'high-panel-main-page']) ?>
<?php endif; ?>

<?php if (Yii::$app->user->isGuest): ?>
    <?php
        if (Yii::$app->request->url !== '/login') {
            echo Html::a('Войти', '/login', ['class'=>'high-panel-login']);
        };
    ?>
<?php else: ?>
        <?php
            if (strpos(Yii::$app->request->url, '/admin')!==0) {
                echo Html::a('Админка', '/admin', ['class'=>'high-panel-admin']);
            }
        ?>
    <?= Html::a('Выйти', '/logout', ['class'=>'high-panel-logout']) ?>
<?php endif; ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= $this->title ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <div class="page">
        <div class="center">
            <header>
                <div class="center-block">
                    <h2><?= Html::encode($this->title) ?></h2>
                </div>
            </header>
            <main class="center-block">
                <div class="high-panel">
                    <?= $this->render('_high_menu'); ?>
                </div>
                <?= $content ?>
            </main>
        </div>
        <footer>

        </footer>
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_login_form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'action'=>'/login',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
        'options'=>[
            'class'=>'login-form'
        ]
    ]); ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'placeholder'=>'Имя']) ?>

    <?= $form->field($model, 'password')->passwordInput(['placeholder'=>'Пароль']) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

<?php ActiveForm::end(); ?>

views/site/_main_menu.php
<?php
use yii\helpers\Html;
?>

<?php
    echo Html::ul($menu_items, ['item' => function($item, $index) {
              return Html::tag('li', Html::a($index, $item, ['class'=>'standart-button']));
                    }, 'class'=>'main-menu']);
?>

views/site/_search_form.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<?php $form = ActiveForm::begin([
        'id' => 'search-model',
        'action'=>'/search',
        'options'=>[
            'class'=>'search-form'
        ]
    ]); ?>

    <?= $form->field($search_model, 'ingredient_one', ['enableLabel'=>false, 'options'=>['class'=>'search-form-field']])->textInput(['class'=>'search-form-field-input', 'placeholder'=>'First']) ?>
    <?= $form->field($search_model, 'ingredient_two', ['enableLabel'=>false, 'options'=>['class'=>'search-form-field']])->textInput(['class'=>'search-form-field-input', 'placeholder'=>'Second']) ?>
    <?= $form->field($search_model, 'ingredient_three', ['enableLabel'=>false, 'options'=>['class'=>'search-form-field']])->textInput(['class'=>'search-form-field-input', 'placeholder'=>'Third']) ?>
    <?= $form->field($search_model, 'ingredient_four', ['enableLabel'=>false, 'options'=>['class'=>'search-form-field']])->textInput(['class'=>'search-form-field-input', 'placeholder'=>'Four']) ?>
    <?= $form->field($search_model, 'ingredient_five', ['enableLabel'=>false, 'options'=>['class'=>'search-form-field']])->textInput(['class'=>'search-form-field-input', 'placeholder'=>'Five']) ?>

    <?php if (!empty($search_message)) echo '<div class="index-message-block">'.$search_message.'</div>'; ?>

    <?= Html::submitButton('Искать', ['class' => 'search-form-button', 'name' => 'login-button']) ?>
<?php ActiveForm::end(); ?>

views/site/_search_results.php
<table class="index-search-results">
    <?php foreach($search_data as $dish): ?>
        <tr>
            <td><?= $dish['name'] ?></td>
            <td class="ingredient-list">(<?= $dish['ingredients'] ?>)</td>
        </tr>
    <?php endforeach; ?>
</table>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = "Ошибка";
?>
<div class="site-error">

    <h3>Возникла ошибка, вернитесь на главную страницу</h3>

    <?= Html::a('Вернуться на главную', '/', ['class' => 'standart-button dish-manage-button']) ?>
</div>

views/site/index.php
<?php
$this->title = 'Мастер кухни';

$menu_items = [
    'Книги рецептов'=>'/books',
    'Поиск по ингредиентам'=>'/search'
];
?>

<?= $this->render('_main_menu', [
        'menu_items'=>$menu_items
]); ?>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход в систему';
?>

<div class="login-page">

    <?= $this->render('_login_form', [
        'model'=>$model,
    ]); ?>
</div>

views/site/search.php
<?php
$this->title = 'Поиск блюд';
?>

<?= $this->render('_search_form', [
        'search_model'=>$search_model,
        'search_message'=>$search_message
    ]); ?>

<?= $this->render('_search_results', [
        'search_data'=>$search_data
    ]); ?>